version: 2.1
orbs:
  bundle-install: toshimaru/bundle-install@0.3.1
jobs:
  rspec:
    docker:
      - image: 'circleci/ruby:3.0.0'
    steps:
      - checkout
      - bundle-install/bundle-install
      - run: bundle exec rspec
