version: 2.1
orbs:
  bundle-install: toshimaru/bundle-install@0.3.1
  rubocop: hanachin/rubocop@0.0.6
jobs:
  rspec:
    docker:
      - image: 'circleci/ruby:3.0.0'
      - image: 'circleci/postgres:12.7'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - bundle-install/bundle-install
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:migrate RAILS_ENV=test
      - run: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - rspec
  rubocop:
    jobs:
      - rubocop/rubocop
  
