version: 2.1
orbs:
  bundle-install: toshimaru/bundle-install@0.3.1
  rubocop: hanachin/rubocop@0.0.6
jobs:
  rspec:
    docker:
      - image: 'circleci/ruby:3.0.0'
      - image: 'circleci/postgres:12.7'
        environment:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - bundle-install/bundle-install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - rspec
  rubocop:
    jobs:
      - rubocop/rubocop