# Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: surprisehr_development

test:
  <<: *default
  database: surprisehr_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
